apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: test-cluster
    region: us-west-2

nodeGroups:
    - name: k8s-1
      instanceType: t2.micro
      desiredCapacity: 3
      iam:
        instanceRoleARN: "arn:aws:iam::341879875473:role/eks_service"
