apiVersion: v1
kind: Service
metadata:
    app: company2vec
    environment: dev
spec:
    type: NodePort
    selector:
        app: company2vec
        environment: dev
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 5000
